[server]
headless = true
# Port configuration is handled by environment-specific scripts
# Local: 8501 (via run_app.py), Replit: 5000 (via main.py), Streamlit Cloud: 8501 (default)

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
